version: "3.8"

services:
    db:
        image: postgres:14.0-alpine
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: ngongkir
        ports:
            - "5432:5432"
volumes:
    postgres-data:
